version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["uvicorn", "source.main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery
    command: ["celery", "-A", "source.celery.celery_app:celery", "worker"]
    depends_on:
      - redis
      - backend
    volumes:
      - .:/app
    user: celeryuser

  celery_beat:
    build: .
    container_name: celery_beat
    command: ["celery", "-A", "source.celery.celery_app:celery", "beat"]
    depends_on:
      - redis
      - backend
    volumes:
      - .:/app
    user: celeryuser

  migrations:
    build: .
    container_name: backend_migrations
    env_file:
      - .env
    depends_on:
      - db
    command: ["alembic", "upgrade", "head"]

volumes:
  postgres_data:
