version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["uvicorn", "source.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  migrations:
    build: .
    container_name: backend_migrations
    env_file:
      - .env
    depends_on:
      - db
    command: ["alembic", "upgrade", "head"]

volumes:
  postgres_data:
