"""get_expirated_to_token

Revision ID: a2c7d12106fe
Revises: b26645f2b181
Create Date: 2024-08-27 20:51:31.339939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c7d12106fe'
down_revision: Union[str, None] = 'b26645f2b181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('expirated', sa.Boolean(), nullable=True))
    op.execute('UPDATE tokens SET expirated = FALSE WHERE expirated IS NULL')
    op.alter_column('tokens', 'expirated', existing_type=sa.Boolean(), nullable=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'expirated')
    # ### end Alembic commands ###
