"""Add event status

Revision ID: ba2fcf6cf847
Revises: aa03db55e4c6
Create Date: 2024-09-16 22:46:20.950281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2fcf6cf847'
down_revision: Union[str, None] = 'aa03db55e4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    event_status_enum = sa.Enum('ENDED', 'ONGOING', 'INCOMING', name='eventstatus')
    event_status_enum.create(op.get_bind())
    op.add_column('events', sa.Column('status', event_status_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'status')
    # ### end Alembic commands ###
